version: "3.4"
services:
  app:
    build:
      context: ../../
      dockerfile: ./Dockerfile-dev
    volumes:
      - ../../:/opt/recogito
      - recogitodata:/opt/recogito/uploads/
    ports:
      networks:
        - default
        - backend
      # will exit otherwise, see <https://stackoverflow.com/a/30177216>
      stdin_open: true
      - 9000:9000

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=recogito
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - backend

  # <https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html>
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  backend:

volumes:
  recogitodata:
  postgresdata:
  esdata:
