version: "3.4"
services:
  app:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - recogitodata:/opt/recogito/uploads/
      - $HOME/application.conf:/opt/recogito/conf/application.conf
    ports:
      - 9000:9000
    networks:
      - default
      - backend
